spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/kodilla_project?allowPublicKeyRetrieval=true&useSSL=false'
    username: kodilla_user
    password: kodilla_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret_key: f73kL2k8krQf9otgApPm3A4kO6Dfg8Jd6Gt3kB1m8dZ6hAl4
